via_points  :
  position:      
    - position: [1.0, 2.0, 0.0]
    - position: [0.0, 2.0, 0.0]
    - position: [0.0, 1.0, 0.0]
    - position: [1.0, 1.0, 0.0]

    - position: [0.0, 2.0, 0.0]
    - position: [2.0, 2.0, 0.0]

    - position: [3.0, 0.0, 0.0]
    - position: [3.0, 2.0, 0.0]
    - position: [4.0, 2.0, 0.0]
    - position: [4.0, 1.0, 0.0]
    - position: [4.5, 1.0, 0.0]
    - position: [4.5, 0.0, 0.0]
    - position: [3.0, 0.0, 0.0]
    - position: [3.0, 1.0, 0.0]
    - position: [4.0, 1.0, 0.0]

    - position: [5.5, 0.0, 0.0]
    - position: [5.5, 2.0, 0.0]
    - position: [6.5, 2.0, 0.0]
    - position: [6.5, 0.0, 0.0]
    - position: [5.5, 0.0, 0.0]

  duration: 1.0 